### ISSUE TITLE
Trouble removing crucible recipes from Mariculture.

### ISSUE THREAD

**Issue by BBoldt** [joshiejack/ModTweaker#61]
Mariculture-Deluxe-1.7.10-161
MineTweaker3-1.7.10-3.0.9B
ModTweaker-1.7.X-0.6-0

Script:
> mods.mariculture.Crucible.removeRecipe(<minecraft:obsidian>);

Error:
> [07/11/2014 21:13:12 PM] [Client thread/INFO]: [CHAT] ERROR: Error executing mariculture.zs: null

Trying to get rid of this crazy recipe that allows for obsidian duplication in my pack:
![](http://i.imgur.com/x7DnBYe.png)

**Comment by joshiejack** [comment]
Fixed with 1.2.4 Mariculture
