### ISSUE TITLE
Crashing with the latest Mariculture

### ISSUE THREAD

**Issue by Yulife** [joshiejack/ModTweaker#62]
So, I updated to Mariculture Deluxe 162 on the jenkins, it has been fine before but now it crashes me on startup with this log:
http://paste.ee/p/9ixJj

Using the official Mariculture on the forum page doesn't crash.

Forge 1235
Latest Jenkins Modtweaker
Latest Jenkins Mariculture

**Comment by joshiejack** [comment]
Fixed with latest mariculture release.
