### ISSUE TITLE
Thaumcraft research not unlocking custom research

### ISSUE THREAD

**Issue by jordsta95** [joshiejack/ModTweaker#69]
Hey there, so I have this script:

mods.thaumcraft.Arcane.addShaped("ASPECTS", <Thaumcraft:blockStoneDevice:2>, "aqua 25, terra 25, perditio 25, ordo 25, ignis 25, aer 25",
[[<Thaumcraft:ItemResource:2>, <Thaumcraft:blockCosmeticSolid:6>,<Thaumcraft:ItemResource:2>],
[<Thaumcraft:blockCosmeticSolid:6>, <Thaumcraft:blockCrystal:6>, <Thaumcraft:blockCosmeticSolid:6>],
[<Thaumcraft:ItemResource:2>, <Thaumcraft:blockCosmeticSolid:6>, <Thaumcraft:ItemResource:2>]]);

Which, as you can see, is supposed to make it so that once the player has researched ASPECTS the player can then use that infusion recipe. However, this research is unlocked by default, and the player is unable to do this recipe. Although, if the player uses the Thaumonomicon cheat sheet to unlock all research, they are magically able to do this recipe.

**Comment by SpitefulFox** [comment]
You're complaining about a custom research, and then an infusion recipe, but this is clearly an arcane recipe.

Furthermore, I can't replicate the problem.  Using the script makes the recipe useable at game start just fine for me.

**Comment by jordsta95** [comment]
Well that is weird, as I have had 2 people who, using that script, could not craft anything. And there is video footage of this too, so I 100% believe the recipe does not work.
