### ISSUE TITLE
[Request] Botania addition - Mana creator

### ISSUE THREAD

**Issue by jordsta95** [joshiejack/ModTweaker#70]
As a pack creator, I would like to create a Botania based pack. But I don't want people to be waiting for mana to build up so that they can craft.
So maybe it would be possible to add a mana generation method? Maybe it would be something like

//flower type,block that makes mana,how much mana is generated
mods.Botania.addFlower(day,<minecraft:dirt>,1);
mods.Botania.addFlower(night,<minecraft:stone>,2);
mods.Botania.addFlower(water,<minecraft:diamond_block,6);

So that means with this code, a dirt block would generate 1 mana a tick, during the daytime, and stone would generate 2 mana a tick, during the night.
But the diamond block would work as the hydreigna (can't spell it :/)

So the flower types, I can think of:
daybloom = day
nightshade = night
hydreigna = water
thermalilly = lava
Kekimurus = cake
Endoflame = furnace

I can't remember the rest of the flowers, but you get what I mean?

**Comment by Yulife** [comment]
Oh god. Maybe @jaredlll08's JSONables will have it in the future.
