### ISSUE TITLE
Tinkers metal casts bug or intended ?

### ISSUE THREAD

**Issue by stricee** [joshiejack/ModTweaker#71]
I love how you can disable the usage of alloys but isnt it possible to stop gold being used for casts?

at the moment the only solotion for gold being used for makeing tool casts is to disable the entire gold melting in tinkers is this hardcoded into TC or Modtweaker unsporting it?

**Comment by evanjohnman** [comment]
Can you post the script code you are trying to use?
It should work. From what I understand, MT can take recipies and delete them, even if they're hard-coded.

**Comment by evanjohnman** [comment]
The removal of casts hasn't been implemented yet. Sorry.

**Comment by evanjohnman** [comment]
mods.tconstruct.Casting.removeBasinRecipe(<minecraft:gold_ingot);
mods.tconstruct.Casting.removeTableRecipe(<minecraft:gold_ingot);

**Comment by evanjohnman** [comment]
Replace the minecraft:gold_ingot with the blank casts name, the re-add the aluminum brass recipe to the list.
