### ISSUE TITLE
[Wiki Suggestion]: Add Flaxbeard and Thermal Expansion Documentation

### ISSUE THREAD

**Issue by Lanse505** [joshiejack/ModTweaker#75]
Quick suggestion would be to add documentation for Thermal Expansion and Flaxbeards steam-powered mod seeing as there is currently none on the Minetweaker>Modtweaker Thread:
http://minetweaker3.powerofbytes.com/wiki/ModTweaker#Mod_Support

A Small suggestion ^^

**Comment by joshiejack** [comment]
You can add the documentation. I'm not going to. I stopped developing ModTweaker. There is nothing to stop anyone else from having added the documentation.
