### ISSUE TITLE
[Request] Ex Nihilo - Barrel.removeRecipe/.addRecipe

### ISSUE THREAD

**Issue by jordsta95** [joshiejack/ModTweaker#76]
Hey there, I was messing around with Ex Nihilo recipes and I found that the composting recipe removal isn't the best way of doing stuff for a few reasons:
1) It only stops 1 item being used
2) It only stops dirt being made

maybe it would be possible to do something like:

mods.exnihilo.Barrel.removeRecipe(<minecraft:dirt>); - which would prevent all composting
" ".Barrel.removeRecipe(<minecraft:clay_block>); - which would prevent people from turning dust into clay
and then have
mods.exnihilo.Barrel.addRecipe(INPUT STACK, % Filled, OUTPUT STACK);
mods.exnihilo.Barrel.addRecipe(<ore:treeSapling>, 20, <minecraft:stone>); - to make stone in a barrel instead of dirt.

**Comment by joshiejack** [comment]
The barrel recipes are hardcoded, this cannot be done.
