### ISSUE TITLE
Can't delete Thaumcraft Iron capped Wand Arcane Recipe

### ISSUE THREAD

**Issue by Dream-Master** [joshiejack/ModTweaker#78]
The shaped recipes i can delete but the Arcane Table recipe still exist.

``````````````````````````````````````````````````````````````````````````````````````````````````````````````
//Iron Caped Wand remove
recipes.remove(<Thaumcraft:WandCasting>);
mods.thaumcraft.Arcane.removeRecipe(<Thaumcraft:WandCasting:1>.withTag({cap: "iron", rod: "wood"}));

//Iron Caped Wand add
recipes.addShaped(<Thaumcraft:WandCasting>, [
[null, <TwilightForest:item.nagaScale>, <Thaumcraft:WandCap>],
[<TwilightForest:item.nagaScale>, <Forestry:oakStick>, <TwilightForest:item.nagaScale>],
[<Thaumcraft:WandCap>, <TwilightForest:item.nagaScale>, null]]);
// -
mods.thaumcraft.Arcane.addShaped("ROD_wood", <Thaumcraft:WandCasting>, "ordo 1", [
[null, <TwilightForest:item.nagaScale>, <Thaumcraft:WandCap>],
[<TwilightForest:item.nagaScale>, <Forestry:oakStick>, <TwilightForest:item.nagaScale>],
[<Thaumcraft:WandCap>, <TwilightForest:item.nagaScale>, null]]);
``````````````````````````````````````````````````````````````````````````````````````````````````````````````

**Comment by Yulife** [comment]
Outdated repo. Post [here](https://github.com/jaredlll08/ModTweaker2/issues).

**Comment by jaredlll08** [comment]
I noticed this without even having to load my game up to confirm, you remove "Thaumcraft:WandCasting:1" but then you add "Thaumcraft:WandCasting"
You did not remove the correct wand, take the ":1" away.

**Comment by Dream-Master** [comment]
I test it with :1 too not changing any thing

**Comment by Dream-Master** [comment]
I try with :* too

**Comment by jaredlll08** [comment]
if you read what I said... I said, take the ":1" AWAY, use /mt hand while holding the iron capped wand

**Comment by Dream-Master** [comment]
I try this too the recipes not disappear.

````````````````````````````````````````````````````````````````````````````````````
mods.thaumcraft.Arcane.removeRecipe(<Thaumcraft:WandCasting>.withTag({aqua: 2500, terra: 2500, ignis: 2500, ordo: 2500, perditio: 2500, aer: 2500}));
mods.thaumcraft.Arcane.removeRecipe(<Thaumcraft:WandCasting:1>.withTag({cap: "iron", rod: "wood"}));
mods.thaumcraft.Arcane.removeRecipe(<Thaumcraft:WandCasting>.withTag({cap: "iron", rod: "wood"}));
``````````````````````````````````````````````````````````````````````````

**Comment by Dream-Master** [comment]
I try all combination. It looks like the recipes not refresh. I see the new and the old recipes.

**Comment by Dream-Master** [comment]
I make many Recipes with mine-modtweaker all ready and i really need help because that Recipes is Game breaking for me.

All Scripts i did:
https://github.com/Dream-Master/DreamCraft
https://github.com/Dream-Master/Mods-Get-Gregged

**Comment by jaredlll08** [comment]
Can you give me a few minutes?

**Comment by Dream-Master** [comment]
Yes sure. 
Sorry i sitting since yesterday and try out many things. Take you time if you find a solution i am very happy.

**Comment by jaredlll08** [comment]
Do you get any messages from minetweaker when loading the world?

**Comment by Dream-Master** [comment]
no not get any error only when i try to make a research refresh

mods.thaumcraft.Research.refreshResearchRecipe("ROD_wood");

give me a Error executing Thaumcraft.zs null (maybe because it is no research)

**Comment by Dream-Master** [comment]
Maybe its Thaumic Nei Plugin make this recipes ?

**Comment by jaredlll08** [comment]
no, I have tested the recipe in the arcane workbench

**Comment by Dream-Master** [comment]
And you can delete it ?

**Comment by jaredlll08** [comment]
I can not delete it, I think thaumcraft prevents the deletion of this specific recipe due to the fact that you need the basic wand to start off with

**Comment by Dream-Master** [comment]
Ok thanks for all your work and sorry. 
I change the iron Wand caps to some other Items (maybe ironwood from TF) and make it only Workbench craftable.
