### ISSUE TITLE
Chisel support nor working

### ISSUE THREAD

**Issue by ChaoticTabris** [joshiejack/ModTweaker#81]
I'm trying to create a chisel group and add variations to it but when i try to load it in-game i get errors saying: "No such member: chisel"

Below is the script i've written:

mods.chisel.Groups.addGroup("andesite");
mods.chisel.Groups.addVariation("andesite", <chisel:andesite>);
mods.chisel.Groups.addVariation("andesite", <UndergroundBiomes:igneousStone:3>);

**Comment by Yulife** [comment]
# 1: Wrong Github.

# 2: There is a [WIP] prefix, if you didn't look.

# 3: It says (0.7+) and that obviously isn't out yet.

Close the issue.

**Comment by ChaoticTabris** [comment]
Really sorry, Yulife. I have no idea how i didn't noticed the [WIP] before it. Wish i could delete this.
