### ISSUE TITLE
Thaumcraft 4 research

### ISSUE THREAD

**Issue by dylanpiera** [joshiejack/ModTweaker#86]
Is it possible to make a research unlocked from start (And all its required research)

i wan't to make some custom infusion recipes and unlock infusion crafting from the start

If this is not possible, Then this is a feature request!

**Comment by Yulife** [comment]
That is a good question! By the way, you are in the wrong repo, [Modtweaker has a new repo](https://github.com/jaredlll08/ModTweaker2).
You could make a custom research with Modtweaker but that would be a waste of time as there already are quite a few researches that unlock from the opening of the Thaumonicon, for example "Aspects of Magic", "Ores", "The Pech" and so on.
Those researches are all valid to be a dependency for your research. 
Simply supply "ASPECTS" in your infusion recipe, like [this](http://puu.sh/gqf8A/4b289cad6a.txt).

**Comment by dylanpiera** [comment]
I don't think thats what i mean,
I ment the research "Infusion" available from start
That is already is researched

**Comment by Yulife** [comment]
Oops! Well.. I guess [this](http://puu.sh/gqfWq/91febd305c.txt) works. The "clearPrereqs" is there because if the parents of the Infusion research don't get deleted, it might screw up a few things.

**Comment by dylanpiera** [comment]
Thanks very much!

**Comment by Yulife** [comment]
No problem! :) Happy modtweaking.
If you are curious about more Thaumcraft 4 Research modifiying, visit [this](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Thaumcraft_4_Support:Research) page.
