### ISSUE TITLE
TConstruct Smeltery Alloys

### ISSUE THREAD

**Issue by Pablode** [joshiejack/ModTweaker#87]
Removing Tinkers Construct smeltery alloys with mods.tconstruct.Smeltery.removeAlloy(..) does not seem to work. Used TConstruct 1.8.2a, together with a lot of mods. Can anyone confirm this?

Example provided:
mods.tconstruct.Smeltery.removeAlloy(<liquid:manyullyn.molten>);

**Comment by Yulife** [comment]
Wrong repo. Look for the /jaredllll08/Modtweaker2 repo.
